development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV['REDISTOGO_URL'] %>
  host: <%= ENV['PRODUCTION_REDIS_HOST'] %>
  port: <%= ENV['PRODUCTION_REDIS_PORT'] %>
  password: <%= ENV['PRODUCTION_REDIS_PASSWORD'] %>
  channel_prefix: redux-messenger-server_production
